### ISSUE TITLE
STM32L43x Option Byte read/write error

### ISSUE THREAD

**Issue by skobbejaap** [sysprogs/openocd#16]
`stm32l4x option_read` and `stm32l4x option_write` uses incorrect base address (or at least for the STM32L43x family of MCUs, I did not verify the Option Byte addresses of other STM32L4x MCUs).

The base address currently used by `OpenOCD` is `0x40022000`, this should be `0x1FFF7800`, and as a result any calls to `stm32l4x option_read` and `stm32l4x option_write` fails to read/write the option bytes of an STM32L43x MCU.

**Comment by sysprogs** [comment]
Thanks, this actually comes from the mainline OpenOCD.
You can submit a bug report to the [OpenOCD mailing list](https://sourceforge.net/p/openocd/mailman/openocd-devel/), and once they fix it, we will pull the fix to our repository as well.
