### ISSUE TITLE
Pin mux and QSPI set up should be done in reset-init, not reset-end

### ISSUE THREAD

**Issue by ali1234** [sysprogs/openocd#5]
https://github.com/sysprogs/openocd/blob/63f1d12608295e04f915ea5b07c4b80315c262ac/tcl/target/stm32h7x_dual_core.cfg#L258

Doing QSPI init at `reset-end` causes it to happen whenever any type of reset happens. This includes `reset run`, in which the CPU is not halted. Then initialization happens while the CPU is running. This leads to a race condition if user code also initializes the QSPI or does pin muxing, with the end result of register corruption and undefined behavior.

This type of initialization should instead be done in `reset-init` according to OpenOCD documentation:

> This [reset-init] is where you would configure PLLs and clocking, set up DRAM so you can download programs that don’t fit in on-chip SRAM, set up pin multiplexing, and so on. (You may be able to switch to a fast JTAG clock rate here, after the target clocks are fully set up.)

and also OpenOCD developers confirm it:

> (11:42:22) PaulFertser: ali1234: some targets use reset-end for disabling watchdog
> (11:42:27) PaulFertser: ali1234: because it makes sense for debugging
> (11:42:37) PaulFertser: alan_o: initialising flash controller centainly doesn't belong there.
> (11:42:41) PaulFertser: ali1234: ^^
> (11:58:47) PaulFertser: ali1234: reset-init handler is usually used to initialise flash/RAM/etc, whatever is needed for flashing the device, and it's called only during "reset init", not even during "reset halt".
> (11:59:17) PaulFertser: ali1234: so "program" script uses "reset init" automatically prior to trying to write to flash.
> (12:04:42) ali1234: so now i understand why you said "it initializes itself"
> (12:05:27) ali1234: because "reset-end" is always run, even when we are not programming - and we only want openocd to init the chip when programming, otherwise the app code should do it
> (12:05:45) ali1234: ie it should do it itself in that case
> (12:16:15) PaulFertser: ali1234: yes, that's what I meant. Code like that belong to reset-init handler and programming procedure should involve "reset init" command somehow. E.g. default handlers for GDB events includes that prior to erasing the flash.

The patch set being developed upstream also performs the initialization in `reset-init`:

http://openocd.zylin.com/#/c/4321/
http://openocd.zylin.com/#/c/4321/7/tcl/board/nucleo-h743zi.cfg <- line 126, triggers qspi_init in `reset-init`

The commit adding stm32h7x_dual_core.cfg claims to be ported from git.ac6.fr, however I cannot find it anywhere in that repository, so it is not clear to me where it came from.

**Comment by sysprogs** [comment]
Thanks very much for pointing this out. We have reviewed the reset logic used in other scripts and updated the **stm32h7x_dual_core.cfg** file per your advice.

**Comment by ali1234** [comment]
Thanks. I'm not sure that everything in that block should be `reset-init` though. Only the call to `qspi_init` at the bottom. Particularly the watchdog configuration looks like it belongs in `reset-end`. The rest I am not sure which is most appropriate.

**Comment by sysprogs** [comment]
Thanks for pointing this out again. Based on a quick look, most of the other scripts are doing similar initialization in `reset-init`, however some of it is done in `examine-end`. It is hard to say what would be the optimal strategy for this without doing extensive testing, so we rolled back the previous implementation, moving only `qspi_init` to `reset-init`.
