### ISSUE TITLE
Is there any to build this project under Ubuntu？

### ISSUE THREAD

**Issue by woniulive** [sysprogs/openocd#7]
I tried to build this project in ubuntu，but failed.
so is it possiable to build under Ubuntu?

**Comment by sysprogs** [comment]
Sorry, we have not tested it on Ubuntu. Our OpenOCD fork is used for Windows builds shipped with [VisualGDB](https://visualgdb.com/), so we only test it on Windows.

**Comment by woniulive** [comment]
I need stm32g4x series support, but official openocd still don't support it.
So can i merge you code to my personal offcial openocd copy so that i can support stm32g4x series.

**Comment by sysprogs** [comment]
Our OpenOCD fork is licensed under the same terms as the original OpenOCD project.
Feel free to merge it into your own fork, although we cannot guarantee that it will work and also cannot provide any support with it.

**Comment by woniulive** [comment]
Thanks even no support.
I will try to build based on official openocd
